name = "IMAS"
uuid = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
authors = ["Orso Meneghini <orso82@gmail.com>"]
version = "7.0.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
CoordinateConventions = "7204ce3a-f536-43d2-be4a-fbed74e90d86"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ExpiringCaches = "bd5c46ae-da38-4b10-bcdd-5005402f2c4f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
FuseExchangeProtocol = "43dcb517-7681-482a-b959-351932bd0b36"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HelpPlots = "5880b2e8-ad0a-48c9-bacd-30dc9c1357e0"
IMASdd = "c5a45a97-b3f9-491c-b9a7-aa88c3bc0067"
IMASutils = "b8e4ee59-9bed-3a6a-a553-8dd24d6374ad"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Jedis = "b89ccfe0-2c5f-46f6-b89b-da3e1c2e286f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
MillerExtendedHarmonic = "c82744c2-dc08-461a-8c37-87ab04d0f9b8"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NaturalNeighbours = "f16ad982-4edb-46b1-8125-78e5a8b5a9e6"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolygonOps = "647866c9-e3ac-4575-94e7-e3d426903924"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Ratios = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractTrees = "0.4"
Compat = "4.10"
Contour = "0.6"
CoordinateConventions = "1"
DSP = "0.8.1"
DataInterpolations = "7, =8.0.0, 8.0.2 - 8"
ExpiringCaches = "1"
ForwardDiff = "0.10, 1"
FuseExchangeProtocol = "2"
GraphRecipes = "0.5"
Graphs = "1"
HelpPlots = "1.1"
IMASdd = "8.3"
IMASutils = "1.5.1"
Interpolations = "0.14.7, 0.15, 0.16.1"
Jedis = "0.3"
LaTeXStrings = "1"
Measurements = "2"
Measures = "0.3"
Memoize = "0.4"
MillerExtendedHarmonic = "1, 2"
NLsolve = "4.5.1"
NaturalNeighbours = "1.3.6"
Optim = "1"
OrderedCollections = "1"
PeriodicTable = "1"
PhysicalConstants = "0.2"
PlotUtils = "1"
Plots = "1"
PolygonOps = "0.1"
Random = "1.11.0"
Ratios = "0.4"
RecipesBase = "1"
Roots = "2"
StaticArrays = "1"
Statistics = "1.11.1"
julia = "1"
